### ISSUE TITLE
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.

### ISSUE THREAD

**Issue by JanghyunJK** [NREL/Wattile#145]
- Unsure if this is just me
- method to replicate
  - executing from current master branch
  - install env with wattile readme
  - execute `entry_point.py` without touching anything
- maybe happened after upping the python version? idk.
- putting as issue before I forget.

```
(wattile) C:\Users\JKIM4\Documents\GitHub\intelligentcampus-pred-analytics>python wattile/entry_point.py
Logging to: exp_dir\output.out, PID: 22224
Traceback (most recent call last):
  File "C:\Users\JKIM4\Anaconda3\envs\wattile\lib\site-packages\pandas\compat\_optional.py", line 138, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\JKIM4\Anaconda3\envs\wattile\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\JKIM4\Anaconda3\envs\wattile\lib\site-packages\tables\__init__.py", line 45, in <module>
    from .utilsextension import get_hdf5_version as _get_hdf5_version
ImportError: DLL load failed while importing utilsextension: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wattile/entry_point.py", line 141, in <module>
    main(configs)
  File "wattile/entry_point.py", line 131, in main
    train_df, val_df = create_input_dataframe(configs)
  File "wattile/entry_point.py", line 59, in create_input_dataframe
    train_df, val_df = bp.prep_for_rnn(configs, data)
  File "C:\Users\JKIM4\Anaconda3\envs\wattile\lib\site-packages\wattile\buildings_processing.py", line 475, in prep_for_rnn
    train_df, val_df = input_data_split(data, configs)
  File "C:\Users\JKIM4\Anaconda3\envs\wattile\lib\site-packages\wattile\buildings_processing.py", line 142, in input_data_split
    test_df.to_hdf(
  File "C:\Users\JKIM4\Anaconda3\envs\wattile\lib\site-packages\pandas\core\generic.py", line 2763, in to_hdf
    pytables.to_hdf(
  File "C:\Users\JKIM4\Anaconda3\envs\wattile\lib\site-packages\pandas\io\pytables.py", line 311, in to_hdf
    with HDFStore(
  File "C:\Users\JKIM4\Anaconda3\envs\wattile\lib\site-packages\pandas\io\pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "C:\Users\JKIM4\Anaconda3\envs\wattile\lib\site-packages\pandas\compat\_optional.py", line 141, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.

(wattile) C:\Users\JKIM4\Documents\GitHub\intelligentcampus-pred-analytics>
```

**Comment by JanghyunJK** [comment]
based on running trainings on HPC at the moment, I think this issue is gone by itself.

**Comment by stephen-frank** [comment]
Can this be closed?

**Comment by haneslinger** [comment]
conda now has [pytables](https://anaconda.org/anaconda/pytables) (i think). We can close this.
